# Generated by Django 6.0.5 on 2026-07-05 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='applicant_profile_image/')),
                ('headline', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.SmallIntegerField(blank=True, null=True)),
                ('current_job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('current_company', models.CharField(blank=True, max_length=200, null=True)),
                ('expected_salary', models.IntegerField()),
                ('linkedin_url', models.URLField(blank=True, max_length=250, null=True)),
                ('github_url', models.URLField(blank=True, max_length=250, null=True)),
                ('portfolio_url', models.URLField(blank=True, max_length=250, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.country')),
                ('skills', models.ManyToManyField(blank=True, null=True, related_name='applicant_skills', to='skills.skills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
