# Generated by Django 6.0.5 on 2026-07-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
