# Generated by Django 6.0.5 on 2026-07-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0002_alter_applicantprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='expected_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
