# Generated by Django 6.0.5 on 2026-07-08 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
        ('profile_management', '0004_employerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='industry.industry'),
        ),
    ]
