# Generated by Django 6.0.5 on 2026-07-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0007_alter_employerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='contact_person_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
