# Generated by Django 6.0.5 on 2026-07-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credential_verification', '0002_alter_emailverificationlink_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverificationlink',
            old_name='unqiue_link',
            new_name='unique_link',
        ),
    ]
