# Generated by Django 6.0.5 on 2026-07-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
    ]
